services:

  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: miniaturedb
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5

#  customer:
#    build:
#      context: ./customer/
#      dockerfile: Dockerfile
#    depends_on:
#      postgres:
#        condition: service_healthy

